Astalem/Models/AstalemViewModels/OrderReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Astalem.Models.AstalemViewModels
{
    public class OrderReportViewModel
    {
        public DateTime From { get; set; }  
        public DateTime To { get; set; }  
        public int OrderCount { get; set; }     
       // public string MaxProviderOrderCount { get; set; }      
        public double AllAmount { get; set; }
        public int OrderCashCount { get; set; }
        public int OrderOnLineCount { get; set; }   
        public int OrderInRoadCount { get; set; }
        public int OrderInAttendCount { get; set; }
        public int OrderFinshedCount { get; set; }
        public int OrderCanceledCount { get; set; } 

    }
}

Astalem/Models/AstalemViewModels/ProviderReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Astalem.Models.AstalemViewModels
{
    public class ProviderReportViewModel
    {
        public string ProviderPhone { get; set; }
        public int OrderCount { get; set; } 
        public int TodayOrderCount { get; set; } 
        public string ProviderName { get; set; }   
        public double AllAmount { get; set; }       
        public double ProviderAmount { get; set; }           
        public string Area { get; set; }          
        public string City { get; set; }

        public string AccountNumber { get; set; }   
        public string AccountName { get; set; } 
        public string BankName { get; set; }    

    }
}

Astalem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Astalem.Models;
using Microsoft.AspNetCore.Authorization;
using Astalem.Data;
using Astalem.Models.AstalemViewModels;
using Microsoft.EntityFrameworkCore;
using jsreport.AspNetCore;
using jsreport.Types;
using System.Web;

namespace Astalem.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private IJsReportMVCService _JsReportMvcService { get; }

        private readonly ApplicationDbContext _context;
        public HomeController(ApplicationDbContext Context, IJsReportMVCService JsReportMVCService)
        {
            _context = Context;
            _JsReportMvcService = JsReportMVCService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IndexViewModel indexViewModel = new IndexViewModel();

           List<City> citys = new List<City>();
            var prv = await _context.Providers.ToListAsync();
            var allAreaAndCity = await _context.Districts.ToListAsync();
            foreach (var item in allAreaAndCity)
            {
                City city = new City();
                city.AreaName = item.DistrictName;
                city.CityName = item.City;
                var provider = prv.Where(m => m.DistrictId == item.Id).ToList();  
                city.CountProviderInArea = provider.Count;
                citys.Add(city);
            }

          
            var clients = await _context.Clients.ToListAsync();
            var providers = await _context.Providers.ToListAsync(); 
            var orders = await _context.Orders.ToListAsync(); 
            var todayOrders = await _context.Orders.Where(m=>m.DateTimeNow.Date == DateTime.Now.Date).ToListAsync(); 
            var todayAmount = await _context.ProviderActiveHistories.Where(m=>m.DateTimeNow.Date == DateTime.Now.Date ).ToListAsync(); 
            var todayAllAmount = await _context.ProviderActiveHistories.ToListAsync(); 
            indexViewModel.ClientCount = clients.Count;
            indexViewModel.ProviderCount= providers.Count;
            indexViewModel.AllOrderCount = orders.Count;
            indexViewModel.TodayOrderCount = todayOrders.Count;
            indexViewModel.TodayAmount = todayAmount.Sum(m=>m.amount);
            indexViewModel.AllAmount = todayAllAmount.Sum(m=>m.amount);
            indexViewModel.Cities = citys.OrderByDescending(m => m.CountProviderInArea).ToList();
            return View(indexViewModel);
        }

        [HttpGet]
        public IActionResult ReportIndex()  
        {
            ViewData["Message"] = "Your application description page.";
            return View();
        }


        [HttpGet]
        public IActionResult OrderReportIndex() 
        {
            ReportTimeViewModel reportTimeViewModel = new ReportTimeViewModel();
            reportTimeViewModel.DateFrom = DateTime.Now.Date;
            reportTimeViewModel.DateTo = DateTime.Now.Date;
            return View(reportTimeViewModel);
        }


        [HttpGet]
      //  [MiddlewareFilter(typeof(JsReportPipeline))]
        public async Task<IActionResult> ProviderReport()
        {


            //string header = "";
            //string footer = "";
            //header = await _JsReportMvcService.RenderViewToStringAsync(HttpContext, RouteData, "header", new { });
            //footer = await _JsReportMvcService.RenderViewToStringAsync(HttpContext, RouteData, "footer", new { });


            var providers =await  _context.Providers.Include(m=>m.District).ToListAsync();
            List<ProviderReportViewModel> providerReportViewModel = new List<ProviderReportViewModel>();
            foreach (var item in providers) 
            {
                ProviderReportViewModel reportViewModel = new ProviderReportViewModel();
                var allAmount=  await _context.ProviderActiveHistories.Where(m => m.ProviderPhone == item.Phone).ToListAsync();
                var ProviderAmount =  await _context.ProviderAccounts.Where(m => m.ProviderPhone == item.Phone).ToListAsync();    
                var count = await _context.Orders.Where(m => m.ProviderPhone == item.Phone).ToListAsync();
                var countToday =  count.Where(m =>  m.DateTimeNow.Date == DateTime.Now.Date).ToList();


                reportViewModel.AccountName = item.BankAccountName;
                reportViewModel.AccountNumber = item.IPanNumber;
                reportViewModel.BankName = item.BankName;
                reportViewModel.AllAmount = allAmount.Sum(s => s.amount);
                reportViewModel.Area = item.District.DistrictName;
                reportViewModel.City = item.District.City;
                reportViewModel.OrderCount =count.Count ;
                reportViewModel.TodayOrderCount =countToday.Count ;
                reportViewModel.ProviderPhone = item.Phone;
                reportViewModel.ProviderName = item.FullName;
                reportViewModel.ProviderAmount = ProviderAmount.Sum(m=>m.Amount);
                providerReportViewModel.Add(reportViewModel);
            }


            //string mss = DateTime.Now.ToString();
            //HttpContext.JsReportFeature()
            //    .Recipe(Recipe.PhantomPdf).OnAfterRender(r => HttpContext.Response.Headers["Content-Disposition"] = @"attachment; filename=" + HttpUtility.UrlEncode(mss) + ".pdf")
            //  .Configure(r => r.Template.Phantom = new Phantom
            //  {
            //      Header = header,
            //      Footer = footer,
            //      HeaderHeight = "3.0cm",
            //      FooterHeight = "3.2cm",
            //      Margin = "{ \"top\": \"-10px\", \"left\": \"0px\", \"right\": \"0px\", \"bottom\": \"-20px\" }",
            //      Format = PhantomFormat.A4
            //  });

            return View(providerReportViewModel.ToList());
        }

        [HttpGet]
        public async Task<IActionResult> OrderReport(DateTime DateTo, DateTime DateFrom) 
        {
            ViewData["Message"] = DateTo;   

            var order =await _context.Orders.Where(m=>m.DateTimeNow.Date >= DateFrom.Date && m.DateTimeNow.Date <= DateTo.Date).ToListAsync();
            OrderReportViewModel orderReport = new OrderReportViewModel();

            orderReport.From =DateFrom.Date;
            orderReport.To = DateTo.Date;
            orderReport.OrderCount = order.Count;
            orderReport.AllAmount = order.Sum(m=>m.Amount);
            orderReport.OrderCashCount = order.Where(m=>m.PayType == "Cash").Count();
            orderReport.OrderOnLineCount = order.Where(m => m.PayType == "OnLine"|| m.PayType == "Online").Count();
            orderReport.OrderInRoadCount = order.Where(m => m.Statues == "4").Count();
            orderReport.OrderInAttendCount = order.Where(m => m.Statues == "5").Count();
            orderReport.OrderFinshedCount = order.Where(m => m.Statues == "1").Count();
            orderReport.OrderCanceledCount = order.Where(m => m.Statues == "2" || m.Statues == "3").Count();

            return View(orderReport);
        }




        [HttpGet]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";
            return View();
        }
        [HttpGet]
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }
        [HttpGet]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Astalem/Controllers/ProviderAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Astalem.Data;
using Astalem.Models.AstalemModel;

namespace Astalem.Controllers
{
    public class ProviderAccountsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProviderAccountsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ProviderAccounts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ProviderAccounts.Include(p => p.Provider);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ProviderAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var providerAccount = await _context.ProviderAccounts
                .Include(p => p.Provider)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (providerAccount == null)
            {
                return NotFound();
            }

            return View(providerAccount);
        }

        // GET: ProviderAccounts/Create
        public IActionResult Create(string phone)
        {
           
            ViewData["allAmount"] = _context.ProviderAccounts.Where(m => m.ProviderPhone == phone).Sum(m => m.Amount);
            ViewData["ProviderPhone"] = phone;
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ActiveProvider(string phone)
        {
            var provider = await _context.Providers.FindAsync(phone);
            provider.ExpirationDate = DateTime.Now;
            _context.Update(provider);
            await _context.SaveChangesAsync();
            return RedirectToAction("ProviderReport", "Home");
        }
        // POST: ProviderAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Amount,DateTimeNow,Type,ProviderPhone")] ProviderAccount providerAccount)
        {
            if (ModelState.IsValid)
            {
                providerAccount.Amount = providerAccount.Amount * -1;
                providerAccount.DateTimeNow = DateTime.Now;
                _context.Add(providerAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction("ProviderReport", "Home");
            }
        //    ViewData["ProviderPhone"] = new SelectList(_context.Providers, "Phone", "Phone", providerAccount.ProviderPhone);
            return View(providerAccount);
        }

        // GET: ProviderAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var providerAccount = await _context.ProviderAccounts.SingleOrDefaultAsync(m => m.Id == id);
            if (providerAccount == null)
            {
                return NotFound();
            }
            ViewData["ProviderPhone"] = new SelectList(_context.Providers, "Phone", "Phone", providerAccount.ProviderPhone);
            return View(providerAccount);
        }

        // POST: ProviderAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Amount,DateTimeNow,Type,ProviderPhone")] ProviderAccount providerAccount)
        {
            if (id != providerAccount.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(providerAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProviderAccountExists(providerAccount.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProviderPhone"] = new SelectList(_context.Providers, "Phone", "Phone", providerAccount.ProviderPhone);
            return View(providerAccount);
        }

        // GET: ProviderAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var providerAccount = await _context.ProviderAccounts
                .Include(p => p.Provider)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (providerAccount == null)
            {
                return NotFound();
            }

            return View(providerAccount);
        }

        // POST: ProviderAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var providerAccount = await _context.ProviderAccounts.SingleOrDefaultAsync(m => m.Id == id);
            _context.ProviderAccounts.Remove(providerAccount);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProviderAccountExists(int id)
        {
            return _context.ProviderAccounts.Any(e => e.Id == id);
        }
    }
}

Astalem/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Astalem/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Astalem/Views/Home/Index.cshtml
@model Astalem.Models.AstalemViewModels.IndexViewModel
@{
    ViewData["Title"] = "Home Page";
}
<br />

<div class="col-md-12">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <div class="panel minimal panel-default">
            <div class="panel-heading clearfix">
                <div class="panel-title">المستخدمين</div>
                <ul class="panel-tool-options"></ul>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row col-with-divider">
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.ProviderCount</h1>
                        <small>عدد المناديب</small>
                    </div>
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.ClientCount</h1>
                        <small>عدد العملاء</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4"></div>
</div>

<div class="col-md-12">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <div class="panel minimal panel-default">
            <div class="panel-heading clearfix">
                <div class="panel-title">الطلبات</div>
                <ul class="panel-tool-options"></ul>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row col-with-divider">
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.TodayOrderCount</h1>
                        <small>عدد طلبات اليوم</small>
                    </div>
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.AllOrderCount</h1>
                        <small>عدد كل الطلبات</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4"></div>

</div>

<div class="col-md-12">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <div class="panel minimal panel-default">
            <div class="panel-heading clearfix">
                <div class="panel-title">الدخل</div>
                <ul class="panel-tool-options"></ul>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row col-with-divider">
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.TodayAmount</h1>
                        <small>دخل اليوم</small>
                    </div>
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.AllAmount</h1>
                        <small>الدخل الكلي</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4"></div>


</div>

<div class="col-md-3"></div>

<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">المناديب</h3>
                <ul class="panel-tool-options">
                    <li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>
                    <li><a data-rel="reload" href="#"><i class="icon-arrows-ccw"></i></a></li>
                    <li><a data-rel="close" href="#"><i class="icon-cancel"></i></a></li>
                </ul>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <td>اسم المدينة</td>
                                <td>اسم الحي</td>
                                <td>عدد المناديب</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Cities)
                            {
                                <tr>
                                    <td>@item.CityName</td>
                                    <td>@item.AreaName</td>
                                    <td>@item.CountProviderInArea</td>
                                </tr>
                            }


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-md-3"></div>

Astalem/Views/Home/OrderReport.cshtml
@model Astalem.Models.AstalemViewModels.OrderReportViewModel

 
  

   


<div class="col-md-12">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <div class="panel minimal panel-default">
            <div class="panel-heading clearfix">
                <div class="panel-title"> من تاريخ @Model.From.Date الي تاريخ @Model.To.Date </div>
                <ul class="panel-tool-options"></ul>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row col-with-divider">
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">  @Model.OrderCount</h1>
                        <small>عدد الطلبات</small>
                    </div>
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">
                            @Model.AllAmount
                        </h1>
                        <small> اجمالي مبالغ الطلبات</small>
                    </div>
                </div>
            </div>




            <div class="panel-body">
                <div class="row col-with-divider">
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.OrderCashCount</h1>
                        <small>عدد الطلبات المدفوعة عن الاستلام</small>
                    </div>
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.OrderOnLineCount</h1>
                        <small> عدد الطلبات المدفوعة الكترونيا</small>
                    </div>
                </div>
            </div>




            <div class="panel-body">
                <div class="row col-with-divider">
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.OrderInRoadCount</h1>
                        <small>عدد الطلبات بالطريق</small>
                    </div>
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.OrderInAttendCount</h1>
                        <small>عدد الطلبات التي تجهز</small>
                    </div>
                </div>
            </div>

            
            

            <div class="panel-body">
                <div class="row col-with-divider">
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.OrderFinshedCount</h1>
                        <small>عدد الطلبات المنتهية</small>
                    </div>
                    <div class="col-xs-6 text-center stack-order">
                        <h1 class="no-margins">@Model.OrderCanceledCount</h1>
                        <small>عدد الطلبات الملغية</small>
                    </div>
                </div>
            </div>










        </div>
    </div>
    <div class="col-md-4"></div>
</div>

Astalem/Views/Home/OrderReportIndex.cshtml
@model Astalem.Models.AstalemViewModels.ReportTimeViewModel
@{
    ViewData["Title"] = "ProviderReportIndex";
}

<form method="get">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-sm-3">
            <div id="date-popup" class="input-group date">
                من تاريخ
                <input type="text" asp-for="DateFrom" data-format="D, dd MM yyyy" class="form-control">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>





    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-sm-3">
            <div id="date-popup1" class="input-group date">
                الي تاريخ
                <input type="text" asp-for="DateTo" data-format="D, dd MM yyyy" class="form-control">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            </div>
        </div>
        <div class="col-lg-3"></div>
    </div>



    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-sm-3">
            <input type="submit" asp-route-to="@Model.DateTo" asp-route-From="@Model.DateFrom" asp-action="OrderReport" asp-controller="Home" class="btn btn-primary btn-block" value="موافق" />


        </div>
        <div class="col-lg-3"></div>
    </div>

</form>

Astalem/Views/Home/ProviderReport.cshtml
@model IEnumerable<Astalem.Models.AstalemViewModels.ProviderReportViewModel>
@using Astalem.Data
@inject ApplicationDbContext _context
@{
  //  Layout =  "~/Views/Shared/_LayoutEmpty.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <td>
                اسم المندوب
            </td>
            <td>
                رقم الهاتف
            </td>

            <td>
                اسم المدينة
            </td>




            <td>
                اسم البنك
            </td>
            <td>
                رقم الحساب
            </td>

            <td>
                اسم صاحب حساب البنك
            </td>





            <td>
                اسم الحي
            </td>
            <td>
                عدد الطلبات اليوم
            </td>

            <td>
                عدد كل الطلبات
            </td>

            <td>
                اجملي دخله للشركة
            </td>

            <td>
                حساب المندوب
            </td>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProviderName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.ProviderPhone)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>




            <td>
                @Html.DisplayFor(modelItem => item.BankName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.AccountNumber)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.AccountName)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TodayOrderCount)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.OrderCount)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.AllAmount)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.ProviderAmount)
            </td>
            <td><a asp-controller="ProviderAccounts" asp-action="Create" asp-route-phone="@item.ProviderPhone">تسديد لمندوب</a></td>
            <td><a asp-controller="Providers" asp-action="Index" asp-route-phone="@item.ProviderPhone"> بيانات المندوب</a></td>
            @if (_context.Providers.SingleOrDefault(m => m.Phone == item.ProviderPhone).ExpirationDate.AddDays(1) <= DateTime.Now)
            {
                <td><a asp-controller="ProviderAccounts" asp-action="ActiveProvider" asp-route-phone="@item.ProviderPhone">تفعيل مندوب </a></td>
            }
            else
            {
                <td>المقدم مفعل</td>
            }
        </tr>
        }
    </tbody>
</table>

Astalem/Views/Home/ReportIndex.cshtml
@{
    ViewData["Title"] = "ReportIndex";
}

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <a asp-action="ProviderReport" asp-controller="Home" class="btn btn-primary btn-block"> المناديب</a>
        <a asp-controller="Home" asp-action="OrderReportIndex" class="btn btn-primary btn-block">تقرير الطلبات</a>
        <div class="col-lg-3"></div>
    </div>
</div>

Astalem/Views/Home/footer.cshtml
@{
    ViewData["Title"] = "footer";
}

Astalem/Views/Home/header.cshtml
@{
    ViewData["Title"] = "header";
}